sudo: required
language: node_js
node_js:
  - 14
services:
  - docker
before_install:
  - npm install
  - CI=true npm run test
  - docker build -t ttoonoott/travis -f Dockerfile.dev .
# script:
#   - docker run -e CI=true ttoonoott/travis npm run test