sudo: required
language: node_js
node_js:
  - 14
services:
  - docker
before_install:
  - docker build -t ttoonoott/travis -f Dockerfile.dev .
script:
  - docker run -e CI=true ttoonoott/travis npm run test